package com.councilgrad.councilgrad.model.enums;

public enum SpecializationType {
    AI_ML,
    DATA_SCIENCE,
    CYBER_SECURITY,
    CLOUD_COMPUTING,
    BUSINESS_ANALYTICS,
    FINANCE,
    MARKETING,
    HUMAN_RESOURCES,
    COMPUTER_SCIENCE,
    INFORMATION_TECHNOLOGY,
    MECHANICAL,
    CIVIL,
    ELECTRONICS,
    BUSINESS_ADMINISTRATION,
    COMPUTER_APPLICATIONS
}
